create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  received_at timestamptz not null default now()
);

alter table public.messages enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.messages to anon, authenticated;

drop policy if exists "Allow anonymous contact inserts" on public.messages;

create policy "Allow anonymous contact inserts"
on public.messages
for insert
to anon, authenticated
with check (
  length(trim(name)) > 0
  and length(trim(email)) > 0
  and length(trim(message)) > 0
);
